# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/.config/wpg/wallpapers/fujisan.png'

# Special
background='#162119'
foreground='#c4c7c5'
cursor='#c4c7c5'

# Colors
color0='#162119'
color1='#72aa80'
color2='#5ba4a6'
color3='#75aec6'
color4='#5a9bc5'
color5='#a6bac7'
color6='#4e83ac'
color7='#c4c7c5'
color8='#505852'
color9='#72aa80'
color10='#5ba4a6'
color11='#75aec6'
color12='#5a9bc5'
color13='#a6bac7'
color14='#4e83ac'
color15='#c4c7c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
