# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/.config/wpg/wallpapers/wafu-bedroom.jpg'

# Special
background='#2b131f'
foreground='#fed0d0'
cursor='#fed0d0'

# Colors
color0='#2b131f'
color1='#a36960'
color2='#ca8961'
color3='#f6d05d'
color4='#6b74a9'
color5='#be8e83'
color6='#e49a5f'
color7='#f9c9ab'
color8='#7f3e61'
color9='#e67a6d'
color10='#feaf67'
color11='#fefe63'
color12='#7887ec'
color13='#feaa93'
color14='#fec967'
color15='#fed0d0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
