# Shell variables
# Generated by 'wal'
wallpaper='startled_kitten.jpg'

# Special
background='#202123'
foreground='#fefeff'
cursor='#fefeff'

# Colors
color0='#202123'
color1='#a96974'
color2='#acb5c7'
color3='#a498a7'
color4='#8b94ac'
color5='#a98394'
color6='#7189aa'
color7='#c7c7c8'
color8='#6d6f76'
color9='#ed768b'
color10='#c7e3ff'
color11='#e1b0ed'
color12='#a0b7f3'
color13='#ef96be'
color14='#80afef'
color15='#fefeff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
