--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/fujisan.png"

-- Special
background="#162119"
foreground="#c4c7c5"
cursor="#c4c7c5"

-- Colors
color0="#162119"
color1="#72aa80"
color2="#5ba4a6"
color3="#75aec6"
color4="#5a9bc5"
color5="#a6bac7"
color6="#4e83ac"
color7="#c4c7c5"
color8="#505852"
color9="#72aa80"
color10="#5ba4a6"
color11="#75aec6"
color12="#5a9bc5"
color13="#a6bac7"
color14="#4e83ac"
color15="#c4c7c5"
