--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/wafu-bedroom.jpg"

-- Special
background="#2b131f"
foreground="#fed0d0"
cursor="#fed0d0"

-- Colors
color0="#2b131f"
color1="#a36960"
color2="#ca8961"
color3="#f6d05d"
color4="#6b74a9"
color5="#be8e83"
color6="#e49a5f"
color7="#f9c9ab"
color8="#7f3e61"
color9="#e67a6d"
color10="#feaf67"
color11="#fefe63"
color12="#7887ec"
color13="#feaa93"
color14="#fec967"
color15="#fed0d0"
