"   _   _   _   _   _  
"  / \ / \ / \ / \ / \ 
" ( v | i | m | r | c )
"  \_/ \_/ \_/ \_/ \_/ 
" 

runtime! config/setup/*.vim
runtime! config/common/*.vim
runtime! config/plugins/common/*.vim config/plugins/vim/*.vim
