#!/bin/dash 

file=$1
base=${file%.*}
suffix=${file##*.}

if [ $# -eq 0 ]; then
  echo "Usage: $0 (file)"
  exit 1
fi

if [ ! -f $file ]; then 
  echo "NO such file called $file"
  exit 1
fi

echo "##Auto compile when the source $1 changed"

# pkill -f "entr compiler" && exit
echo "$file" | entr -s "compiler $file; and echo '======Running======';and ./$base; and echo '======Finish======='"
