#!/bin/dash

file="$HOME/.cache/dwm/mymood.txt"
iconfile="$HOME/.cache/dwm/mymoodicons.txt"
input=""
usage() {
  echo "Usage: $0 (input|ask|choose|help)"
}

readfromterminal() {
  read input
}

askprompt() {
  input=$(zenity --entry --title="mymood" --text="Enter whatever you want.")
}

seticon() {
  echo $input > $file
}

chooseicon() {
  cat $iconfile | rofi -dmenu -p "icon" > $file
}

display() {
  cat $file
}

#main
case $1 in 
  input|-i|--input|i) readfromterminal && seticon;;
  a|ask) askprompt && seticon;;
  choose|c) chooseicon;;
  help|h) usage;;
  *) display;;
esac
