#!/bin/dash

usage () {
  echo "Usage: $0 (help)"
}

rofioption () {
  echo "quicknote (Gnvim)
timer
calendar
dynwal (dynamic background)
wallpaper in sxiv
screenshot
calculator haskell ghci
spacefm (file manager)
config awesomewm
config rightclickmenu
xkill
view (tail) startx log
daily terminal" | rofi -dmenu -p "lanuncher"
# weather
# mydwmstatus kill
# mymood choose
# mymood askprompt
# htop
# slock
}

execute () {
  case $(rofioption) in
    *Gnvim*) gnvim;;
    # *emacs*) emacsclient --create-frame;;
    timer) timer;;
    calendar) zenity --calendar;;
    weather) weather show;;
    dynwal*) dynamicwallpaper;;
    wallpaper*) sxiv ~/Pictures/Wallpaper;;
    screenshot) screenshot.sh;;
    'mydwmstatus kill') mydwmstatus kill;;
    'daily terminal') st -e tmux attach || st -e tmux ;;
    'mymood choose') mymood choose;;
    'mymood askprompt') mymood ask;;
    'config awesomewm') gnvim ~/.config/awesome/rc.lua;;
    'config rightclickmenu') gnvim ~/.scripts/rightclickmenu;;
    *ghci*) st -e ghci;;
    spacefm*) spacefm;;
    htop) st -e htop;;
    xkill) xkill;;
    slock) slock;;
    *startx*) st -e tail -f ~/.cache/xorg_startx.log;;
  esac
}


# main
case "$1" in
  -h|-help|h|help) usage;exit 0 ;;
  *) execute ;;
esac

# vim: filetype=sh
