#!/bin/env dash

SSID=$($HOME"/.scripts/getssid")
# echo $SSID

case "$2" in
	CONNECTED)
		notify-send "WPA supplicant: connection established" "Connect to $SSID";
		;;
	DISCONNECTED)
		notify-send "WPA supplicant: connection lost" "Disconnect with $1 $SSID";
		;;
esac

# vim: filetype=sh
