#+TITLE: config.org

* Table of contents :TOC:
- [[#about][about]]
  - [[#doom-emacs][doom emacs]]
  - [[#notes][notes]]
  - [[#files][files]]
- [[#common][common]]
  - [[#user-name-and-email][user name and email]]
  - [[#line-number][line number]]
  - [[#browser-url][browser url]]
- [[#doom][doom]]
  - [[#font][font]]
  - [[#theme][theme]]
- [[#org][org]]
  - [[#directory][directory]]
  - [[#open-file][open file]]
- [[#packages][packages]]
  - [[#org-][org-*]]
  - [[#other-packages][other packages]]

* about
** doom emacs
[[https://github.com/hlissner/doom-emacs][doom-emacs]] repo

** notes
- [[file:config.el][config.el]] is generated from [[file:config.org][config.org]] by enabling =literate= flag in [[file:init.el][init.el]] followed by ~doom sync~

** files
- [[file:config.org][config.org]] contains various configurations
- [[file:init.el][init.el]] specifies the modules doom loads
- [[file:packages.el][packages.el]] specifies the additional packages you would install

* common
** user name and email
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Alex Lai"
      user-mail-address "alex@alexlai.xyz")
#+end_src

** line number
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type t)
#+end_src

** browser url
#+begin_src emacs-lisp :tangle yes
(setq browse-url-browser-function 'browse-url-firefox)
#+end_src


* doom
** font
Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:

+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
#+begin_src emacs-lisp :tangle yes
(setq doom-font (font-spec :family "DejaVuSansMono" :size 14))
#+end_src

** theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:
#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'doom-one)
#+end_src


* org
** directory
#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/Nextcloud/org/")
#+end_src

** open file
#+begin_src emacs-lisp :tangle yes
;; open apps
(setq org-file-apps
      '((auto-mode . emacs)
        (directory . emacs)
        ("\\.mm\\'" . default)
        ("\\.x?html?\\'" . default)
        ("\\.pdf\\'" . default)
        ("\\.png\\'" . "sxiv \"%s\"" )
        ("\\.jpg\\'" . "sxiv \"%s\"" )
        ("\\.svg\\'" . "sxiv \"%s\"" )
        ("\\.gif\\'" . "mpv \"%s\""  )
        ("\\.mkv\\'" . "mpv \"%s\""  )
        ("\\.mp3\\'" . "mpv \"%s\""  )
        ("\\.mp4\\'" . "mpv \"%s\""  )
        ))
#+end_src



* packages
- functions
  - `load!' for loading external *.el files relative to this one
  - `use-package' for configuring packages
  - `after!' for running code after a package has loaded
  - `add-load-path!' for adding directories to the `load-path', relative to
    this file. Emacs searches the `load-path' when you load packages with
    `require' or `use-package'.
  - `map!' for binding new keys
   
** org-*
*** org-roam
#+begin_src emacs-lisp :tangle yes
(use-package org-roam
  :ensure t
  :config
  (setq org-roam-directory "~/Nextcloud/roam")
  )
#+end_src

*** org-roam-server
#+begin_src emacs-lisp :tangle yes
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-label-truncate t
        org-roam-server-label-truncate-length 60
        org-roam-server-label-wrap-length 20))
#+end_src

*** org-journal
#+begin_src emacs-lisp :tangle yes
(after! org-journal
(setq org-journal-file-type 'weekly)
  )
#+end_src

#+RESULTS:
: weekly

*** org-re-reveal
#+begin_src emacs-lisp :tangle yes
(setq org-re-reveal-root "http://cdn.jsdelivr.net/reveal.js/3.0.0/")
#+end_src

#+RESULTS:
: http://cdn.jsdelivr.net/reveal.js/3.0.0/

** other packages
*** simplenote
#+begin_src emacs-lisp :tangle yes
(require 'simplenote2)
(load-file "~/.config/doom/simplenote.el")
(simplenote2-setup)
#+end_src

(use-package simplenote2
  :ensure t
  :config
  (load-file "~/.config/doom/simplenote.el")
  (simplenote2-setup)
  )

*** deft
#+begin_src emacs-lisp :tangle yes
(after! deft
  (setq deft-directory "~/Nextcloud/roam")
  )
#+end_src
