#!/bin/dash
usage() {
  echo "Usage: $0 (help|update)"
}

result=""
getstatus() {
  h=$(date +%H)
  if [ $h -ge 7 -a $h -lt 11 ]; then # 7 - 11
    result="🌅"
  elif [ $h -ge 11 -a $h -lt 15 ]; then # 11 - 15
    result="🌞"
  elif [ $h -ge 15 -a $h -lt 19 ]; then # 15 - 19
    result="🍁"
  elif [ $h -ge 19 -a $h -lt 23 ]; then # 19 - 23
    result="🌜"
  else  # 23 - 7
    result="🛌"
  fi
}

update_awesome() {
  echo "mydayornight.text = \"$result\"" | awesome-client 
}


case $1 in 
  help|h) usage;;
  update|u) getstatus && update_awesome;;
  *) getstatus && echo $result;;
esac

# vim: syntax=sh
