#!/bin/dash

file="$HOME/.cache/mymood/mymood.txt"
iconfile="$HOME/.cache/mymood/mymoodicons.txt"
input=""
usage() {
  echo "Usage: $0 (input|ask|choose|help)"
}

readfromterminal() {
  read input
}

askprompt() {
  input=$(zenity --entry --title="mymood" --text="Enter whatever you want.")
}

seticon() {
  echo $input > $file
  # awesomewm
  icon=$(cat $file)
  echo "mymood.text = \"$icon\"" | awesome-client 
}

chooseicon() {
  input=`cat $iconfile | rofi -dmenu -p "icon"`
}

display() {
  cat $file
}

#main
case $1 in 
  input|-i|--input|i) readfromterminal && seticon;;
  a|ask) askprompt && seticon;;
  choose|c) chooseicon && seticon;;
  *help|*h) usage;;
  *) display;;
esac

# vim: filetype=sh
