#!/bin/dash

MYMOOD_CACHE_DIR="$XDG_CACHE_HOME/mymood"
file=$MYMOOD_CACHE_DIR"/mymood.txt"
iconfile=$MYMOOD_CACHE_DIR"/mymoodicons.txt"
input=""
usage() {
  echo "Usage: $0 (input|ask|choose|help)"
}

readfromterminal() {
  read input
}

askprompt() {
  input=$(zenity --entry --title="mymood" --text="Enter whatever you want.")
}

seticon() {
  echo $input > $file
  # awesomewm
  icon=$(cat $file)
  echo "mymood.text = \"$icon\"" | awesome-client 
}

chooseicon() {
  input=`cat $iconfile | rofi -dmenu -p "icon"`
}


display() {
  cat $file
}

#main
if [ ! -d $MYMOOD_CACHE_DIR ]; then
  mkdir $MYMOOD_CACHE_DIR
  touch $file $iconfile
fi
case $1 in 
  input|-i|--input|i) readfromterminal && seticon;;
  a|ask) askprompt && seticon;;
  choose|c) chooseicon && seticon;;
  # e|emoji) choosefromemoji && seticon;;
  *help|*h) usage;;
  *) display;;
esac

# vim: filetype=sh
