#!/bin/dash
usage() {
  echo "Usage: $0 (help|update)"
}

INTERFACE="wlan0"
result=""
getstatus() {
  # status=$(wpa_cli -i $INTERFACE status | grep "^ssid" | cut -d '=' -f 2)
  # status=$(iwctl station $INTERFACE show | awk '/Connected network/ {print $3}')
  status=$(iwctl station $INTERFACE show | awk '/Connected network/ {for (i=3;i<=NF;i++) print $i""FS}')
  if [ status != "" ]; then
     result=" $status"
  fi
}

update_awesome() {
  echo "mywifi.text = \"$result\"" | awesome-client 
}


case $1 in 
  help|h) usage;;
  update|u) getstatus && update_awesome;;
  *) getstatus && echo $result;;
esac

# vim: syntax=sh
