#!/bin/dash
usage() {
  echo "Usage: $0 (help|update)"
}

CARD="wlan0"
result=""
getstatus() {
  status=$(wpa_cli -i $CARD status | grep "^ssid" | cut -d '=' -f 2)
  if [ status != "" ]; then
     result=" $status"
  fi
}

update_awesome() {
  echo "mywifi.text = \"$result\"" | awesome-client 
}


case $1 in 
  help|h) usage;;
  update|u) getstatus && update_awesome;;
  *) getstatus && echo $result;;
esac

# vim: syntax=sh
