#!/bin/dash

termcmd="$TERMINAL -e fish -c"

usage () {
  echo "Usage: $0 (help)"
}

rofioption () {
  echo "quicknote (Gnvim)
timer
dynwal (dynamic background)
wallpaper in sxiv
screenshot
calculator haskell ghci
config awesomewm
config rightclickmenu
xkill
view (tail) startx logs
daily terminal" | rofi -dmenu -p "lanuncher"
# spacefm (file manager)
# calendar
# weather
# mydwmstatus kill
# mymood choose
# sxhkd restart (Simple X hotkey daemon)
# mymood askprompt
# htop
# slock
}

execute () {
  case $(rofioption) in
    *Gnvim*) gnvim;;
    # *emacs*) emacsclient --create-frame;;
    timer) timer;;
    calendar) zenity --calendar;;
    weather) weather show;;
    dynwal*) dynamicwallpaper;;
    wallpaper*) sxiv ~/Pictures/Wallpaper;;
    screenshot) screenshot.sh;;
    'mydwmstatus kill') mydwmstatus kill;;
    'daily terminal') $termcmd tmux attach || $termcmd tmux ;;
    'mymood choose') mymood choose;;
    'mymood askprompt') mymood ask;;
    'config awesomewm') $termcmd nvim ~/.config/awesome/rc.lua;;
    'config rightclickmenu') $termcmd nvim ~/.scripts/rightclickmenu;;
    *ghci*) $termcmd ghci;;
    spacefm*) spacefm;;
    htop) $termcmd htop;;
    xkill) xkill;;
    slock) slock;;
    *sxhkd*) pkill sxhkd; sxhkd;;
    *startx*) 
      $termcmd tail -f $XDG_CACHE_HOME/xorg_startx.log &
      $termcmd tail -f $XDG_CACHE_HOME/xorg_startx_stdout.log
      ;;
  esac
}


# main
case "$1" in
  -h|-help|h|help) usage;exit 0 ;;
  *) execute ;;
esac

# vim: filetype=sh
