--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/Library_Night.jpg"

-- Special
background="#221e1c"
foreground="#c7c6c6"
cursor="#c7c6c6"

-- Colors
color0="#221e1c"
color1="#ab9890"
color2="#aa7e6a"
color3="#aa6237"
color4="#aa7250"
color5="#b08c47"
color6="#6c7ea2"
color7="#c7c6c6"
color8="#595654"
color9="#ab9890"
color10="#aa7e6a"
color11="#aa6237"
color12="#aa7250"
color13="#b08c47"
color14="#6c7ea2"
color15="#c7c6c6"
