--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/violet_evergarden_doll.png"

-- Special
background="#272524"
foreground="#c9c8c8"
cursor="#c9c8c8"

-- Colors
color0="#272524"
color1="#c6bcb9"
color2="#ad8f83"
color3="#ad7258"
color4="#c5b29d"
color5="#7977ab"
color6="#a598a5"
color7="#c9c8c8"
color8="#5d5b5a"
color9="#c6bcb9"
color10="#ad8f83"
color11="#ad7258"
color12="#c5b29d"
color13="#7977ab"
color14="#a598a5"
color15="#c9c8c8"
