--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/Watercolor_Sunset_Clouds.png"

-- Special
background="#231809"
foreground="#c8c5c1"
cursor="#c8c5c1"

-- Colors
color0="#231809"
color1="#b17b30"
color2="#c6aa47"
color3="#ab9d53"
color4="#c5bc6f"
color5="#91ab67"
color6="#67a97d"
color7="#c8c5c1"
color8="#5a5146"
color9="#b17b30"
color10="#c6aa47"
color11="#ab9d53"
color12="#c5bc6f"
color13="#91ab67"
color14="#67a97d"
color15="#c8c5c1"
