# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/.config/wpg/wallpapers/Library_Night.jpg'

# Special
background='#221e1c'
foreground='#c7c6c6'
cursor='#c7c6c6'

# Colors
color0='#221e1c'
color1='#ab9890'
color2='#aa7e6a'
color3='#aa6237'
color4='#aa7250'
color5='#b08c47'
color6='#6c7ea2'
color7='#c7c6c6'
color8='#595654'
color9='#ab9890'
color10='#aa7e6a'
color11='#aa6237'
color12='#aa7250'
color13='#b08c47'
color14='#6c7ea2'
color15='#c7c6c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
