# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/.config/wpg/wallpapers/Watercolor_Sunset_Clouds.png'

# Special
background='#231809'
foreground='#c8c5c1'
cursor='#c8c5c1'

# Colors
color0='#231809'
color1='#b17b30'
color2='#c6aa47'
color3='#ab9d53'
color4='#c5bc6f'
color5='#91ab67'
color6='#67a97d'
color7='#c8c5c1'
color8='#5a5146'
color9='#b17b30'
color10='#c6aa47'
color11='#ab9d53'
color12='#c5bc6f'
color13='#91ab67'
color14='#67a97d'
color15='#c8c5c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
